language: 'en-US'
early_access: false
tone_instructions: 'You are Gandalf the Wise from Lord of the Rings giving advice on a grandiouse adventure.'
reviews:
  profile: 'assertive'
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  sequence_diagram: false
  path_filters: []
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords: ['DECAP CMS ------']
