#Decap CMS settings
#local_backend: true

backend:
  name: github
  branch: main
  repo: FroloEH/KVsite
  base_url: http://localhost:4321
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: 'src/images/uploads'
public_folder: 'src/images/uploads'
publish_mode: editorial_workflow
logo_url: src/images/LogoTransparent.png

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'src/content/pages/home.md'
        fields:
          # HERO
          - { label: 'Hero_header1', name: 'hero_header1', widget: 'string' }
          - { label: 'Hero_header2', name: 'hero_header2', widget: 'string' }
          - {
              label: 'Hero_Button1_Text',
              name: 'hero_button1_text',
              widget: 'string',
            }
          - {
              label: 'Hero_Button1_Link',
              name: 'hero_button1_link',
              widget: 'string',
            }
          - {
              label: 'Hero_Button2_Text',
              name: 'hero_button2_text',
              widget: 'string',
            }
          - {
              label: 'Hero_Button2_Link',
              name: 'hero_button2_link',
              widget: 'string',
            }
          - { label: 'Hero_Image', name: 'hero_image', widget: 'image' }
          # USP
          - { label: 'Usp1_header', name: 'usp1_header', widget: 'string' }
          - { label: 'Usp1_Popis', name: 'usp1_text', widget: 'string' }
          - { label: 'Usp1_Image', name: 'usp1_image', widget: 'image' }
          - { label: 'Usp2_header', name: 'usp2_header', widget: 'string' }
          - { label: 'Usp2_Popis', name: 'usp2_text', widget: 'string' }
          - { label: 'Usp2_Image', name: 'usp2_image', widget: 'image' }
          - { label: 'Usp3_header', name: 'usp3_header', widget: 'string' }
          - { label: 'Usp3_Popis', name: 'usp3_text', widget: 'string' }
          - { label: 'Usp3_Image', name: 'usp3_image', widget: 'image' }
          # PARTNERS
          - {
              label: 'Partners_header',
              name: 'partners_header',
              widget: 'string',
            }
          - {
              label: 'Partners_this_year_header',
              name: 'partners_this_year_header',
              widget: 'string',
            }
          - {
              label: 'Partners_last_year_header',
              name: 'partners_last_year_header',
              widget: 'string',
            }
          - {
              label: 'Partners_this_year',
              name: 'partners_this_year',
              widget: 'relation',
              collection: 'partners',
              multiple: true,
              searchFields: ['name'],
              valueField: 'name',
              displayFields: ['name'],
            }
          - {
              label: 'Partners_last_year',
              name: 'partners_last_year',
              widget: 'relation',
              collection: 'partners',
              multiple: true,
              searchFields: ['name'],
              valueField: 'name',
              displayFields: ['name'],
            }

  - name: 'event'
    label: 'Event'
    folder: 'src/content/events'
    create: true
    slug: '{{nadpis}}'
    fields:
      - { label: 'Nadpis', name: 'nadpis', widget: 'string' }
      - { label: 'Dátum', name: 'datum', widget: 'string' }
      - { label: 'Miesto', name: 'miesto', widget: 'string' }
      - { label: 'Instagram', name: 'instagram', widget: 'string' }
      - { label: 'Facebook Event', name: 'linkFbEvent', widget: 'string' }
      - { label: 'Discord', name: 'discord', widget: 'string' }
      - { label: 'Obrázok', name: 'obrazok', widget: 'image' }
      - { label: 'Podnadpis', name: 'podnadpis', widget: 'string' }
      - { label: 'Anotácia', name: 'anotacia', widget: 'string' }

  - name: 'partners'
    label: 'Partners'
    folder: 'src/content/partners'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }
