#Decap CMS settings
#local_backend: true

backend:
  name: github
  branch: main
  repo: FroloEH/KVsite
  base_url: https://k-vsite.vercel.app/
  preview_context: vercel/deployment
  squash_merges: true
  commit_messages:
    create: DECAP CMS ------ Create {{collection}} “{{slug}}”
    update: DECAP CMS ------ Update {{collection}} “{{slug}}”
    delete: DECAP CMS ------ Delete {{collection}} “{{slug}}”
    uploadMedia: DECAP CMS ------ Upload “{{path}}”
    deleteMedia: DECAP CMS ------ Delete “{{path}}”

media_folder: 'frontend/src/images/uploads'
public_folder: 'frontend/src/images/uploads'
publish_mode: editorial_workflow
logo_url: /LogoTransparent.png
site_url: https://vercel.live/open-feedback
display_url: https://github.com/FroloEH/KVsite/pulls

collections:
  - label: 'Pages'
    name: 'pages'
    preview_path: k-vsite-git-cms-pages{{slug}}-froloehs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'frontend/src/content/pages/home.md'
        fields:
          # HERO
          - { label: 'Hero_header1', name: 'hero_header1', widget: 'string' }
          - { label: 'Hero_header2', name: 'hero_header2', widget: 'string' }
          - {
              label: 'Hero_Button1_Text',
              name: 'hero_button1_text',
              widget: 'string',
            }
          - {
              label: 'Hero_Button1_Link',
              name: 'hero_button1_link',
              widget: 'string',
            }
          - {
              label: 'Hero_Button2_Text',
              name: 'hero_button2_text',
              widget: 'string',
            }
          - {
              label: 'Hero_Button2_Link',
              name: 'hero_button2_link',
              widget: 'string',
            }
          - { label: 'Hero_Image', name: 'hero_image', widget: 'image' }
          # USP
          - { label: 'Usp1_header', name: 'usp1_header', widget: 'string' }
          - { label: 'Usp1_Popis', name: 'usp1_text', widget: 'string' }
          - { label: 'Usp1_Image', name: 'usp1_image', widget: 'image' }
          - { label: 'Usp2_header', name: 'usp2_header', widget: 'string' }
          - { label: 'Usp2_Popis', name: 'usp2_text', widget: 'string' }
          - { label: 'Usp2_Image', name: 'usp2_image', widget: 'image' }
          - { label: 'Usp3_header', name: 'usp3_header', widget: 'string' }
          - { label: 'Usp3_Popis', name: 'usp3_text', widget: 'string' }
          - { label: 'Usp3_Image', name: 'usp3_image', widget: 'image' }
          # PARTNERS
          - {
              label: 'Partners_header',
              name: 'partners_header',
              widget: 'string',
            }
          - {
              label: 'Partners_this_year_header',
              name: 'partners_this_year_header',
              widget: 'string',
            }
          - {
              label: 'Partners_last_year_header',
              name: 'partners_last_year_header',
              widget: 'string',
            }
          - {
              label: 'Partners_this_year',
              name: 'partners_this_year',
              widget: 'relation',
              collection: 'partners',
              multiple: true,
              searchFields: ['name'],
              valueField: 'name',
              displayFields: ['name'],
            }
          - {
              label: 'Partners_last_year',
              name: 'partners_last_year',
              widget: 'relation',
              collection: 'partners',
              multiple: true,
              searchFields: ['name'],
              valueField: 'name',
              displayFields: ['name'],
            }

          # TEAM
          - { label: 'Team_header', name: 'team_header', widget: 'string' }
          - { label: 'Team_text', name: 'team_text', widget: 'string' }
          - {
              label: 'Team_call_to_action_text',
              name: 'team_call_to_action_text',
              widget: 'string',
            }
          - {
              label: 'Team_call_to_action_link',
              name: 'team_call_to_action_link',
              widget: 'string',
            }
          - {
              label: 'Team_members',
              name: 'team_members',
              widget: 'relation',
              collection: 'team_member',
              multiple: true,
              searchFields: ['name'],
              valueField: 'name',
              displayFields: ['name'],
            }
          # PLAYER STORIES
          - {
              label: 'Player_stories_header',
              name: 'player_stories_header',
              widget: 'string',
            }
          - {
              label: 'Player_stories_text',
              name: 'player_stories_text',
              widget: 'string',
            }
          - {
              label: 'Player_stories_collection',
              name: 'player_stories_collection',
              widget: 'relation',
              collection: 'player_stories',
              multiple: true,
              searchFields: ['title'],
              valueField: 'title',
              displayFields: ['title'],
            }

      - label: 'Footer'
        name: 'footer'
        file: 'frontend/src/content/pages/footer.md'
        fields:
          - {
              label: 'Footer call to action text',
              name: 'footer_cta_text',
              widget: 'string',
            }
          - {
              label: 'Footer call to action link',
              name: 'footer_cta_link',
              widget: 'string',
            }
          - {
              label: 'Footer call to action button text',
              name: 'footer_cta_button_text',
              widget: 'string',
            }
          - {
              label: 'Footer 1st column header',
              name: 'footer_1st_column_header',
              widget: 'string',
            }
          - {
              label: 'Footer 1st column links',
              name: 'footer_1st_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }
          - {
              label: 'Footer 2nd column header',
              name: 'footer_2nd_column_header',
              widget: 'string',
            }
          - {
              label: 'Footer 2nd column links',
              name: 'footer_2nd_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }
          - {
              label: 'Footer 3rd column header',
              name: 'footer_3rd_column_header',
              widget: 'string',
            }
          - {
              label: 'Footer 3rd column subheader',
              name: 'footer_3rd_column_subheader',
              widget: 'string',
            }
          - {
              label: 'Footer 3rd column links',
              name: 'footer_3rd_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }

      - label: 'Header'
        name: 'header'
        file: 'frontend/src/content/pages/header.md'
        fields:
          - {
              label: 'Header 1st column header',
              name: 'header_1st_column_header',
              widget: 'string',
            }
          - {
              label: 'Header 1st column links',
              name: 'header_1st_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }
          - {
              label: 'Header 2nd column header',
              name: 'header_2nd_column_header',
              widget: 'string',
            }
          - {
              label: 'Header 2nd column links',
              name: 'header_2nd_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }
          - {
              label: 'Header 3rd column header',
              name: 'header_3rd_column_header',
              widget: 'string',
            }
          - {
              label: 'Header 3rd column links',
              name: 'header_3rd_column_links',
              widget: 'list',
              fields:
                [
                  { label: Link text, name: link_text, widget: string },
                  { label: Target, name: link_target, widget: string },
                ],
            }

      - label: 'Thank you'
        name: 'thank_you'
        file: 'frontend/src/content/pages/thank_you.md'
        fields:
          - {
              label: 'Thank you page title',
              name: 'thank_you_title',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Thank you text',
              name: 'body',
              widget: 'markdown',
              required: true,
            }
          - {
              label: 'Thank you image',
              name: 'thank_you_image',
              widget: 'image',
            }

      - label: 'LARP Rules'
        name: 'larp_rules'
        file: 'frontend/src/content/pages/larp-rules.md'
        fields:
          - {
              label: 'LARP rules page title',
              name: 'larp_rules_title',
              widget: 'string',
            }
          - {
              label: 'Background image',
              name: 'background_image',
              widget: 'image',
            }
          - { label: 'Rules intro', name: 'rules_intro', widget: 'markdown' }
          - {
              label: 'Basic rules title',
              name: 'basic_rules_title',
              widget: 'string',
            }
          - {
              label: 'Basic rules description',
              name: 'basic_rules_description',
              widget: 'string',
            }
          - {
              label: 'Basic rules intro',
              name: 'basic_rules_intro',
              widget: 'markdown',
            }
          - {
              label: 'Basic rules parts',
              name: 'basic_rules_parts',
              widget: 'list',
              fields:
                [
                  { label: 'Part title', name: 'part_title', widget: 'string' },
                  {
                    label: 'Part description',
                    name: 'part_description',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Class rules title',
              name: 'class_rules_title',
              widget: 'string',
            }
          - {
              label: 'Class rules description',
              name: 'class_rules_description',
              widget: 'string',
            }
          - {
              label: 'Class rules intro',
              name: 'class_rules_intro',
              widget: 'markdown',
            }
          - {
              label: 'Class rules parts',
              name: 'class_rules_parts',
              widget: 'list',
              fields:
                [
                  { label: 'Part title', name: 'part_title', widget: 'string' },
                  {
                    label: 'Part description',
                    name: 'part_description',
                    widget: 'string',
                  },
                ],
            }
          - { label: 'Errata title', name: 'errata_title', widget: 'string' }
          - {
              label: 'Errata description',
              name: 'errata_description',
              widget: 'string',
            }
          - { label: 'Errata intro', name: 'errata_intro', widget: 'markdown' }
          - {
              label: 'Errata parts',
              name: 'errata_parts',
              widget: 'list',
              fields:
                [
                  { label: 'Part title', name: 'part_title', widget: 'string' },
                  {
                    label: 'Part description',
                    name: 'part_description',
                    widget: 'string',
                  },
                ],
            }
      - label: 'Current LARP event'
        name: 'current_larp_event'
        file: 'frontend/src/content/pages/current-larp-event.md'
        fields:
          - { label: 'Najnovšia udalosť', name: 'current_larp_event', widget: 'relation', collection: 'events', searchFields: ['title'], valueField: 'title', displayFields: ['title'] }
          - { label: 'Veľký text nad zápletkami', name: 'storyIntroText', widget: 'string', default: 'Na čo sa môžeš tešiť?' }
          - { label: 'Obrázok pri zápletkách', name: 'storyImage', widget: 'image' }
          - { label: 'Id eventu v tootoot.fm', name: 'tootoot_id', widget: 'string', hint: 'Napríklad: 65bd0d301b234e08804169cb, nájdeš ho v url konkrétneho eventu na tootoot stránke. Netreba login práva.' }
          - { label: 'Nadpis nad lístkami', name: 'ticketsTitle', widget: 'string', default: 'Lístky' }
          - { label: 'Text nad lístkami', name: 'ticketsText', widget: 'markdown' }
          - {
              label: 'Popis archivovanej akcie',
              name: 'archive_text',
              widget: 'string',
              default: 'Pokračovanie nabudúce',
            }
          - {
              label: 'Text výzvi na odoberanie newsletteru',
              name: 'newsletter_text',
              widget: 'string',
              default: 'Zisti medzi prvými kedy bude ďalšia hra.',
            }
          - {
              label: 'Text tlačítka výzvi na odoberanie newsletteru',
              name: 'newsletter_button_text',
              default: 'Odoberať',
              widget: 'string',
            }

      - label: 'Contact settings and socials'
        name: 'contact_settings'
        file: 'frontend/src/content/pages/contact-settings.md'
        fields:
          - {
            label: 'Email',
            name: 'email',
            widget: 'string',
            required: true,
          }
          - {
            label: 'Facebook',
            name: 'facebook',
            widget: 'string',
            required: true,
          }
          - {
            label: 'Discord',
            name: 'discord',
            widget: 'string',
            required: true,
          }
          - {
            label: 'Instagram',
            name: 'instagram',
            widget: 'string',
            required: true,
          }
          - {
            label: 'Newsletter Link',
            name: 'newsletter_link',
            widget: 'string',
            required: true,
          }

  - name: 'document_pages'
    label: 'Document pages'
    folder: 'frontend/src/pages'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Názov', name: 'title', widget: 'string' }
      - { label: 'Text', name: 'body', widget: 'markdown' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../layouts/DocumentLayout.astro',
        }

  - name: 'event'
    label: 'Event'
    folder: 'frontend/src/content/events'
    preview_path: k-vsite-git-cms-event{{slug}}-froloehs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Nadpis', name: 'title', widget: 'string' }
      - { label: 'Dátum', name: 'date', widget: 'string' }
      - { label: 'Miesto', name: 'place', widget: 'string' }
      - { label: 'Facebook Event', name: 'linkFbEvent', widget: 'string' }
      - { label: 'Obrázok', name: 'image', widget: 'image' }
      - { label: 'Podnadpis', name: 'subTitle', widget: 'string' }
      - { label: 'Anotácia', name: 'annotation', widget: 'string' }
      - { label: 'Zápletka 1 nadpis', name: 'story1Title', widget: 'string' }
      - { label: 'Zápletka 1 text', name: 'story1Text', widget: 'string' }
      - { label: 'Zápletka 2 nadpis', name: 'story2Title', widget: 'string' }
      - { label: 'Zápletka 2 text', name: 'story2Text', widget: 'string' }
      - { label: 'Zápletka 3 nadpis', name: 'story3Title', widget: 'string' }
      - { label: 'Zápletka 3 text', name: 'story3Text', widget: 'string' }
      - { label: 'Archivovať akciu', name: 'archived', widget: 'boolean' }

  - name: 'partners'
    label: 'Partners'
    folder: 'frontend/src/content/partners'
    preview_path: k-vsite-git-cms-partners{{slug}}-froloehs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }

  - name: 'team_member'
    label: 'Team Member'
    folder: 'frontend/src/content/team'
    preview_path: k-vsite-git-cms-team_member{{slug}}-froloehs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }

  - name: 'player_stories'
    label: 'Player Stories'
    folder: 'frontend/src/content/player_stories'
    preview_path: k-vsite-git-cms-player_stories{{slug}}-froloehs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Story', name: 'story', widget: 'text' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - {
          label: 'Event',
          name: 'event',
          widget: 'relation',
          collection: 'event',
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
          multiple: false,
        }
